### ISSUE TITLE
Gem is not found.

### ISSUE THREAD

**Issue by niedfelj** [spree-contrib/spree_legacy_return_authorizations#1]
Has this been published to rubygems?

**Comment by athal7** [comment]
it has not, please install from github

**Comment by niedfelj** [comment]
Ok, well maybe someone should change the install instructions then?

**Comment by athal7** [comment]
cleaning it up now, will publish

**Comment by athal7** [comment]
https://rubygems.org/gems/spree_legacy_return_authorizations, thanks for your patience
