### ISSUE TITLE
`alias_method': undefined method `awaiting_returns?' for class `Spree::Order' (NameError)

### ISSUE THREAD

**Issue by niedfelj** [spree-contrib/spree_legacy_return_authorizations#2]
awaiting_returns? method appears to not exist within the Spree codebase?

You guys are trying to alias_method_chain on line 9 of order_decorator, when I think you just want to alias_method.  Is anyone actually using this code?

**Comment by athal7** [comment]
you are right, it should be 'awaiting_return?'

**Comment by athal7** [comment]
one sec, fixing this up
